#!/bin/bash

# Check if env folder exists
if [ ! -d "env" ]; then
    echo "Creating virtual environment..."
    python -m venv env
    echo "Installing dependencies..."
    env/bin/python -m pip install --upgrade pip
    env/bin/python -m pip install -r requirements.txt
fi

# Run the application
env/bin/python app.py
